# Copyright 2016 The Kubernetes Authors.
# Copyright 2020 Philippe Martin
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

parts:
- name: Workloads
  chapters:
  - name: Pod
    group: ""
    version: v1
  - name: Container
    group: ""
    version: v1
  - name: EphemeralContainer
    group: ""
    version: v1
  - name: PodTemplate
    group: ""
    version: v1
  - name: ReplicationController
    group: ""
    version: v1
  - name: ReplicaSet
    group: apps
    version: v1
  - name: Deployment
    group: apps
    version: v1
  - name: StatefulSet
    group: apps
    version: v1
  - name: ControllerRevision
    group: apps
    version: v1
  - name: DaemonSet
    group: apps
    version: v1
  - name: Job
    group: batch
    version: v1
  - name: CronJob
    group: batch
    version: v1beta1
  - name: CronJob
    group: batch
    version: v2alpha1
  - name: HorizontalPodAutoscaler
    group: autoscaling
    version: v1
  - name: HorizontalPodAutoscaler
    group: autoscaling
    version: v2beta2
  - name: PriorityClass
    group: scheduling.k8s.io
    version: v1
  - name: PodPreset
    group: settings.k8s.io
    version: v1alpha1
- name: Services
  chapters:
  - name: Service
    group: ""
    version: v1
  - name: Endpoints
    group: ""
    version: v1
  - name: EndpointSlice
    group: discovery.k8s.io
    version: v1beta1
  - name: Ingress
    group: networking.k8s.io
    version: v1beta1
  - name: IngressClass
    group: networking.k8s.io
    version: v1beta1
- name: Config and Storage
  chapters:
  - name: ConfigMap
    group: ""
    version: v1
  - name: Secret
    group: ""
    version: v1
  - name: Volume
    group: ""
    version: v1
  - name: PersistentVolumeClaim
    group: ""
    version: v1
  - name: PersistentVolume
    group: ""
    version: v1
  - name: StorageClass
    group: storage.k8s.io
    version: v1
  - name: VolumeAttachment
    group: storage.k8s.io
    version: v1
  - name: CSIDriver
    group: storage.k8s.io
    version: v1
  - name: CSINode
    group: storage.k8s.io
    version: v1
- name: Authentication
  chapters:
  - name: ServiceAccount
    group: ""
    version: v1
  - name: TokenRequest
    group: authentication.k8s.io
    version: v1
  - name: TokenReview
    group: authentication.k8s.io
    version: v1
  - name: CertificateSigningRequest
    group: certificates.k8s.io
    version: v1beta1
- name: Authorization
  chapters:
  - name: LocalSubjectAccessReview
    group: authorization.k8s.io
    version: v1
  - name: SelfSubjectAccessReview
    group: authorization.k8s.io
    version: v1
  - name: SelfSubjectRulesReview
    group: authorization.k8s.io
    version: v1
  - name: SubjectAccessReview
    group: authorization.k8s.io
    version: v1
  - name: ClusterRole
    group: rbac.authorization.k8s.io
    version: v1
  - name: ClusterRoleBinding
    group: rbac.authorization.k8s.io
    version: v1
  - name: Role
    group: rbac.authorization.k8s.io
    version: v1
  - name: RoleBinding
    group: rbac.authorization.k8s.io
    version: v1
- name: Policies
  chapters:
  - name: LimitRange
    group: ""
    version: v1
  - name: ResourceQuota
    group: ""
    version: v1
  - name: NetworkPolicy
    group: networking.k8s.io
    version: v1
  - name: PodDisruptionBudget
    group: policy
    version: v1beta1
  - name: PodSecurityPolicy
    group: policy
    version: v1beta1
- name: Extend
  chapters:
  - name: CustomResourceDefinition
    group: apiextensions.k8s.io
    version: v1
  - name: MutatingWebhookConfiguration
    group: admissionregistration.k8s.io
    version: v1
  - name: ValidatingWebhookConfiguration
    group: admissionregistration.k8s.io
    version: v1
- name: Cluster
  chapters:
  - name: Node
    group: ""
    version: v1
  - name: Namespace
    group: ""
    version: v1
  - name: Event
    group: ""
    version: v1
  - name: ComponentStatus
    group: ""
    version: v1
  - name: APIService
    group: apiregistration.k8s.io
    version: v1
  - name: Lease
    group: coordination.k8s.io
    version: v1
  - name: RuntimeClass
    group: node.k8s.io
    version: v1beta1
  - name: AuditSink
    group: auditregistration.k8s.io
    version: v1alpha1
  - name: FlowSchema
    group: flowcontrol.apiserver.k8s.io
    version: v1alpha1
  - name: PriorityLevelConfiguration
    group: flowcontrol.apiserver.k8s.io
    version: v1alpha1
  - name: Binding
    group: ""
    version: v1
- name: Common Definitions
  chapters:
  - name: IntOrString
    key: "io.k8s.apimachinery.pkg.util.intstr.IntOrString"
  - name: JSONSchemaProps
    group: "apiextensions.k8s.io"
    version: "v1"
  - name: LabelSelector
    group: ""
    version: "v1"
  - name: ListMeta
    group: ""
    version: "v1"
  - name: LocalObjectReference
    group: ""
    version: "v1"
  - name: MicroTime
    group: ""
    version: "v1"
  - name: ObjectMeta
    group: ""
    version: "v1"
  - name: ObjectReference
    group: ""
    version: "v1"
  - name: Quantity
    key: "io.k8s.apimachinery.pkg.api.resource.Quantity"
  - name: Time
    group: ""
    version: "v1"
